#!/usr/bin/env python3
"""Extract focused binary windows around top Group B RAM-anchor targets."""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
FLASH = REPO_ROOT / "data" / "raw" / "bcm_p_flash.bin"
LOOSE_CSV = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_ram_anchor_loose_contexts.csv"
OUT_CSV = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_target_windows.csv"
OUT_MD = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_target_windows.md"

TARGETS = {
    ("0x0C9", "0x03FF84BB"),
    ("0x3D1", "0x03FF84BB"),
    ("0x3E9", "0x03FF81C1"),
    ("0x3E9", "0x03FF81C5"),
    ("0x3E9", "0x03FF43E7"),
    ("0x3E9", "0x03FF43FB"),
    ("0x3E9", "0x03FF43FF"),
}
RADIUS = 0x60


def parse_hex(value: str) -> int:
    return int(value, 16)


def merge_offsets(offsets: list[int]) -> list[tuple[int, int, list[int]]]:
    if not offsets:
        return []
    windows: list[tuple[int, int, list[int]]] = []
    start = offsets[0] - RADIUS
    end = offsets[0] + RADIUS
    hits = [offsets[0]]
    for offset in offsets[1:]:
        candidate_start = offset - RADIUS
        candidate_end = offset + RADIUS
        if candidate_start <= end:
            end = max(end, candidate_end)
            hits.append(offset)
        else:
            windows.append((max(0, start), end, hits))
            start = candidate_start
            end = candidate_end
            hits = [offset]
    windows.append((max(0, start), end, hits))
    return windows


def main() -> int:
    data = FLASH.read_bytes()
    by_target: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)

    with LOOSE_CSV.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            key = (row["frame_id"], row["ram_address"])
            if key not in TARGETS:
                continue
            if row["known_structured_load"] != "no":
                continue
            if row["preceding_op_family"] != "possible-write-or-bitop-family":
                continue
            by_target[key].append(row)

    csv_rows: list[dict[str, str]] = []
    md_lines = [
        "# BCM Group B Focused Target Windows",
        "",
        "Generated by `tools/bcm_group_b_target_windows.py`.",
        "Offsets are file offsets in `data/raw/bcm_p_flash.bin`.",
        "",
    ]

    for key in sorted(by_target):
        frame_id, ram_address = key
        rows = sorted(by_target[key], key=lambda row: parse_hex(row["offset_position"]))
        windows = merge_offsets([parse_hex(row["offset_position"]) for row in rows])
        md_lines.extend([f"## `{frame_id}` / `{ram_address}`", ""])
        for index, (start, end, hits) in enumerate(windows):
            end = min(end, len(data))
            blob = data[start:end]
            hit_text = ", ".join(f"0x{hit:06X}" for hit in hits)
            csv_rows.append(
                {
                    "frame_id": frame_id,
                    "ram_address": ram_address,
                    "window_index": str(index),
                    "window_start": f"0x{start:06X}",
                    "window_end": f"0x{end:06X}",
                    "hit_offsets": hit_text,
                    "bytes": blob.hex(" ").upper(),
                }
            )
            md_lines.append(f"### Window {index}: `0x{start:06X}-0x{end:06X}`")
            md_lines.append("")
            md_lines.append(f"- Hit offsets: {hit_text}")
            md_lines.append("")
            md_lines.append("```text")
            for line_start in range(0, len(blob), 16):
                chunk = blob[line_start : line_start + 16]
                md_lines.append(f"0x{start + line_start:06X}: {chunk.hex(' ').upper()}")
            md_lines.append("```")
            md_lines.append("")

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "frame_id",
                "ram_address",
                "window_index",
                "window_start",
                "window_end",
                "hit_offsets",
                "bytes",
            ],
        )
        writer.writeheader()
        writer.writerows(csv_rows)

    OUT_MD.write_text("\n".join(md_lines), encoding="utf-8")
    print(f"wrote {len(csv_rows)} windows to {OUT_CSV} and {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
