#!/usr/bin/env python3
"""Map RAM accesses inside focused Group B target windows."""

from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
WINDOWS = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_target_windows.csv"
OUT_CSV = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_window_ram_map.csv"
OUT_MD = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_window_ram_map.md"
SHORT_GP_BASE = 0x04000000


def u16le(data: bytes, offset: int) -> int:
    return data[offset] | (data[offset + 1] << 8)


def s16(value: int) -> int:
    return value - 0x10000 if value >= 0x8000 else value


def parse_bytes(text: str) -> bytes:
    return bytes.fromhex(text)


def map_accesses(blob: bytes, base: int) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    pos = 0
    while pos + 8 <= len(blob):
        if blob[pos] == 0x40 and blob[pos + 1] == 0x56:
            high = u16le(blob, pos + 2)
            op = blob[pos + 4 : pos + 6].hex().upper()
            raw = u16le(blob, pos + 6)
            ram = (high << 16) + s16(raw)
            rows.append(
                {
                    "offset": f"0x{base + pos:06X}",
                    "op": op,
                    "kind": "absolute",
                    "ram_address": f"0x{ram:08X}",
                }
            )
            pos += 2
            continue

        if pos + 4 <= len(blob) and blob[pos] in (0x24, 0x25, 0x26, 0x2A, 0x2E, 0x2F, 0x84, 0x85, 0x86, 0xA4, 0xA5, 0xAD, 0xAF, 0xE3, 0xE5, 0xEA):
            op1 = blob[pos + 1]
            if op1 in (0x47, 0x4F, 0x57, 0x5F, 0x67, 0x6F, 0x77, 0x7F, 0x87, 0x8F):
                raw = u16le(blob, pos + 2)
                ram = SHORT_GP_BASE + s16(raw)
                if 0x03FF0000 <= ram <= 0x04000000:
                    rows.append(
                        {
                            "offset": f"0x{base + pos:06X}",
                            "op": blob[pos : pos + 2].hex().upper(),
                            "kind": "short-gp",
                            "ram_address": f"0x{ram:08X}",
                        }
                    )
        pos += 1
    return rows


def main() -> int:
    out_rows: list[dict[str, str]] = []
    per_window_counts: dict[str, Counter[str]] = {}

    with WINDOWS.open(newline="", encoding="utf-8") as f:
        for window in csv.DictReader(f):
            base = int(window["window_start"], 16)
            accesses = map_accesses(parse_bytes(window["bytes"]), base)
            key = f"{window['frame_id']} {window['ram_address']} {window['window_index']} {window['window_start']}"
            per_window_counts[key] = Counter(access["ram_address"] for access in accesses)
            for access in accesses:
                out_rows.append(
                    {
                        "frame_id": window["frame_id"],
                        "target_ram": window["ram_address"],
                        "window_index": window["window_index"],
                        "window_start": window["window_start"],
                        "window_end": window["window_end"],
                        "access_offset": access["offset"],
                        "op": access["op"],
                        "kind": access["kind"],
                        "ram_address": access["ram_address"],
                    }
                )

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "frame_id",
                "target_ram",
                "window_index",
                "window_start",
                "window_end",
                "access_offset",
                "op",
                "kind",
                "ram_address",
            ],
        )
        writer.writeheader()
        writer.writerows(out_rows)

    total_counts = Counter(row["ram_address"] for row in out_rows)
    op_counts = Counter(row["op"] for row in out_rows)
    lines = [
        "# BCM Group B Target Window RAM Map",
        "",
        "Generated by `tools/bcm_group_b_window_ram_map.py`.",
        "This scans the focused target windows for short-GP and absolute RAM",
        "access shapes, so the surrounding local RAM structs are visible.",
        "",
        "## Most Common RAM Addresses",
        "",
        "| RAM address | Count |",
        "|---:|---:|",
    ]
    for ram, count in total_counts.most_common(30):
        lines.append(f"| `{ram}` | {count} |")

    lines.extend(["", "## Most Common Access Opcodes", "", "| Opcode | Count |", "|---:|---:|"])
    for op, count in op_counts.most_common(20):
        lines.append(f"| `{op}` | {count} |")

    lines.extend(["", "## Densest Windows", "", "| Window | Unique RAM addresses | Top RAM addresses |", "|---|---:|---|"])
    for key, counts in sorted(per_window_counts.items(), key=lambda item: -len(item[1]))[:20]:
        top = ", ".join(f"`{ram}` x{count}" for ram, count in counts.most_common(8))
        lines.append(f"| `{key}` | {len(counts)} | {top} |")

    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(out_rows)} RAM access rows to {OUT_CSV} and {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
