#!/usr/bin/env python3
"""Cluster repeated Group B RAM-anchor contexts into state-machine pairs."""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
LOOSE_CSV = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_ram_anchor_loose_contexts.csv"
OUT_CSV = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_state_machine_clusters.csv"
OUT_MD = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_state_machine_clusters.md"


def parse_hex(value: str) -> int:
    return int(value, 16)


def load_unique_contexts() -> list[dict[str, str]]:
    seen: set[tuple[str, str, str]] = set()
    rows: list[dict[str, str]] = []
    with LOOSE_CSV.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["known_structured_load"] != "no":
                continue
            if row["preceding_op_family"] != "possible-write-or-bitop-family":
                continue
            key = (row["ram_address"], row["offset_position"], row["preceding_op"])
            if key in seen:
                continue
            seen.add(key)
            rows.append(row)
    return sorted(rows, key=lambda row: (row["ram_address"], parse_hex(row["offset_position"])))


def main() -> int:
    rows = load_unique_contexts()
    by_offset = {(row["ram_address"], parse_hex(row["offset_position"])): row for row in rows}

    out_rows: list[dict[str, str]] = []
    used: set[tuple[str, int]] = set()

    for row in rows:
        ram = row["ram_address"]
        offset = parse_hex(row["offset_position"])
        if (ram, offset) in used:
            continue
        mate = by_offset.get((ram, offset + 6))
        if mate is not None:
            used.add((ram, offset))
            used.add((ram, offset + 6))
            out_rows.append(
                {
                    "ram_address": ram,
                    "cluster_start": f"0x{offset:06X}",
                    "cluster_end": f"0x{offset + 6:06X}",
                    "kind": "paired-offsets-plus-6",
                    "opcodes": f"{row['preceding_op']},{mate['preceding_op']}",
                    "context_bytes": row["context_bytes"],
                }
            )
        else:
            used.add((ram, offset))
            out_rows.append(
                {
                    "ram_address": ram,
                    "cluster_start": f"0x{offset:06X}",
                    "cluster_end": f"0x{offset:06X}",
                    "kind": "single",
                    "opcodes": row["preceding_op"],
                    "context_bytes": row["context_bytes"],
                }
            )

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["ram_address", "cluster_start", "cluster_end", "kind", "opcodes", "context_bytes"],
        )
        writer.writeheader()
        writer.writerows(out_rows)

    pair_counts = Counter(row["ram_address"] for row in out_rows if row["kind"] == "paired-offsets-plus-6")
    all_counts = Counter(row["ram_address"] for row in out_rows)
    lines = [
        "# BCM Group B State-Machine Cluster Report",
        "",
        "Generated by `tools/bcm_group_b_state_machine_clusters.py`.",
        "This deduplicates frame aliases and groups offset hits that occur as",
        "paired accesses six bytes apart, a pattern visible in the repeated",
        "`0x03FF84BB` state-machine blocks.",
        "",
        "## Summary",
        "",
        "| RAM anchor | Clusters | paired +6 clusters |",
        "|---:|---:|---:|",
    ]
    for ram, count in all_counts.most_common():
        lines.append(f"| `{ram}` | {count} | {pair_counts.get(ram, 0)} |")

    lines.extend(["", "## `0x03FF84BB` Paired Clusters", ""])
    for row in out_rows:
        if row["ram_address"] != "0x03FF84BB" or row["kind"] != "paired-offsets-plus-6":
            continue
        lines.append(f"- `{row['cluster_start']}` / `{row['cluster_end']}` opcodes `{row['opcodes']}`")

    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(out_rows)} clusters to {OUT_CSV} and {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
