#!/usr/bin/env python3
"""Create a focused markdown report from loose Group B RAM-anchor contexts."""

from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
IN_CSV = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_ram_anchor_loose_contexts.csv"
OUT_MD = REPO_ROOT / "analysis" / "generated" / "bcm_group_b_ram_anchor_target_report.md"


def parse_hex(value: str) -> int:
    return int(value, 16)


def merge_windows(offsets: list[int], radius: int = 0x40) -> list[tuple[int, int, int]]:
    if not offsets:
        return []
    ranges: list[tuple[int, int, int]] = []
    start = offsets[0] - radius
    end = offsets[0] + radius
    count = 1
    for offset in offsets[1:]:
        candidate_start = offset - radius
        candidate_end = offset + radius
        if candidate_start <= end:
            end = max(end, candidate_end)
            count += 1
        else:
            ranges.append((max(0, start), end, count))
            start, end, count = candidate_start, candidate_end, 1
    ranges.append((max(0, start), end, count))
    return ranges


def main() -> int:
    with IN_CSV.open(newline="", encoding="utf-8") as f:
        rows = [
            row
            for row in csv.DictReader(f)
            if row["known_structured_load"] == "no"
            and row["preceding_op_family"] == "possible-write-or-bitop-family"
        ]

    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["frame_id"], row["ram_address"])].append(row)

    ranked = sorted(grouped.items(), key=lambda item: (-len(item[1]), item[0]))

    lines: list[str] = [
        "# BCM Group B RAM Anchor Target Report",
        "",
        "Generated by `tools/bcm_ram_anchor_target_report.py` from loose RAM-anchor contexts.",
        "These are not proven writes; they are the best manual-disassembly targets",
        "where a Group B RAM anchor appears after an opcode family that is not one",
        "of the already understood load forms.",
        "",
        "## Top Candidates",
        "",
        "| Rank | Frame(s) | RAM anchor | Candidate contexts | Dominant opcodes | Best windows |",
        "|---:|---|---:|---:|---|---|",
    ]

    for rank, ((frame_id, ram_address), entries) in enumerate(ranked[:16], start=1):
        offsets = sorted(parse_hex(row["offset_position"]) for row in entries)
        op_counts = Counter(row["preceding_op"] for row in entries)
        dominant = ", ".join(f"{op}:{count}" for op, count in op_counts.most_common(5))
        windows = merge_windows(offsets)
        best_windows = ", ".join(
            f"`0x{start:06X}-0x{end:06X}` ({count})" for start, end, count in windows[:4]
        )
        lines.append(
            f"| {rank} | `{frame_id}` | `{ram_address}` | {len(entries)} | {dominant} | {best_windows} |"
        )

    lines.extend(
        [
            "",
            "## Detail",
            "",
        ]
    )

    for (frame_id, ram_address), entries in ranked[:16]:
        offsets = sorted(parse_hex(row["offset_position"]) for row in entries)
        op_counts = Counter(row["preceding_op"] for row in entries)
        lines.extend(
            [
                f"### `{frame_id}` / `{ram_address}`",
                "",
                f"- Candidate contexts: {len(entries)}",
                f"- Opcode families: {', '.join(f'`{op}` x{count}' for op, count in op_counts.most_common())}",
                "- Suggested windows:",
            ]
        )
        for start, end, count in merge_windows(offsets)[:8]:
            lines.append(f"  - `0x{start:06X}-0x{end:06X}` ({count} offset hit(s))")
        lines.append("- Example contexts:")
        for row in sorted(entries, key=lambda item: parse_hex(item["offset_position"]))[:8]:
            lines.append(
                f"  - `{row['offset_position']}` op `{row['preceding_op']}`: `{row['context_bytes']}`"
            )
        lines.append("")

    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote target report to {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
