#!/usr/bin/env python3
"""Compare native Corsa E body payloads across saved key-state captures."""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
LOG_DIR = REPO_ROOT / "data" / "can_logs"
OUT_MD = REPO_ROOT / "analysis" / "generated" / "native_body_state_deltas.md"
FOCUS_IDS = ["0F1", "12A", "135", "137", "139", "160", "1F1", "451", "4E1", "514"]
LINE_RE = re.compile(r"^\((?P<ts>[0-9.]+)\)\s+\S+\s+(?P<id>[0-9A-Fa-f]+)#(?P<data>[0-9A-Fa-f]*)")


@dataclass(frozen=True)
class StateCapture:
    state: str
    file_name: str


STATE_CAPTURES = [
    StateCapture("keyoff", "corsa_e_opc_ecumaster_bcm_combined_keyoff.candump"),
    StateCapture("keyon", "corsa_e_opc_ecumaster_bcm_combined_keyon.candump"),
    StateCapture("keyon_startcar", "corsa_e_opc_ecumaster_bcm_combined_keyon_startcar.candump"),
    StateCapture("engine_running", "corsa_e_opc_ecumaster_read_engine_running.candump"),
]


def parse_log(path: Path) -> dict[str, Counter[str]]:
    rows: dict[str, Counter[str]] = defaultdict(Counter)
    with path.open("r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            match = LINE_RE.match(line.strip())
            if not match:
                continue
            can_id = match.group("id").upper()
            if can_id not in FOCUS_IDS:
                continue
            rows[can_id][match.group("data").upper()] += 1
    return rows


def bytes_from_hex(payload: str) -> list[int]:
    return list(bytes.fromhex(payload))


def byte_delta(base: str, other: str) -> str:
    base_bytes = bytes_from_hex(base)
    other_bytes = bytes_from_hex(other)
    parts = []
    for index, (left, right) in enumerate(zip(base_bytes, other_bytes)):
        if left != right:
            parts.append(f"b{index}:{left:02X}->{right:02X}")
    if len(base_bytes) != len(other_bytes):
        parts.append(f"dlc:{len(base_bytes)}->{len(other_bytes)}")
    return ", ".join(parts) if parts else "same"


def top_payload(counter: Counter[str]) -> tuple[str, int]:
    if not counter:
        return "", 0
    return counter.most_common(1)[0]


def format_top(counter: Counter[str], limit: int = 4) -> str:
    if not counter:
        return ""
    return ", ".join(f"`{payload}` x{count}" for payload, count in counter.most_common(limit))


def main() -> int:
    by_state: dict[str, dict[str, Counter[str]]] = {}
    for capture in STATE_CAPTURES:
        path = LOG_DIR / capture.file_name
        if not path.exists():
            raise FileNotFoundError(path)
        by_state[capture.state] = parse_log(path)

    lines = [
        "# Native Body State Deltas",
        "",
        "Generated by `tools/can_native_body_state_deltas.py` from saved Corsa E",
        "key-state captures. These deltas compare dominant observed payloads and are",
        "intended to identify ignition/run/body-context replay candidates for bench",
        "IPC wake experiments.",
        "",
        "## Dominant Payloads By State",
        "",
        "| ID | keyoff | keyon | keyon_startcar | engine_running |",
        "|---:|---|---|---|---|",
    ]

    for can_id in FOCUS_IDS:
        cells = []
        for capture in STATE_CAPTURES:
            cells.append(format_top(by_state[capture.state].get(can_id, Counter()), limit=2))
        lines.append(f"| `{can_id}` | " + " | ".join(cells) + " |")

    lines.extend([
        "",
        "## Dominant Payload Byte Deltas",
        "",
        "Each row compares the most common payload for the state against the most",
        "common `keyoff` payload for the same CAN ID.",
        "",
        "| ID | keyoff dominant | keyon delta | keyon_startcar delta | engine_running delta |",
        "|---:|---|---|---|---|",
    ])

    for can_id in FOCUS_IDS:
        keyoff_payload, keyoff_count = top_payload(by_state["keyoff"].get(can_id, Counter()))
        if not keyoff_payload:
            continue
        delta_cells = []
        for state in ["keyon", "keyon_startcar", "engine_running"]:
            payload, count = top_payload(by_state[state].get(can_id, Counter()))
            if not payload:
                delta_cells.append("")
            else:
                delta_cells.append(f"`{payload}` x{count}: {byte_delta(keyoff_payload, payload)}")
        lines.append(f"| `{can_id}` | `{keyoff_payload}` x{keyoff_count} | " + " | ".join(delta_cells) + " |")

    lines.extend([
        "",
        "## Replay Implications",
        "",
        "- Payloads whose dominant bytes change from keyoff to keyon are better",
        "  ignition/run-context candidates than payloads that stay identical.",
        "- `0F1` is a high-rate cycle; compare its set membership rather than only",
        "  one dominant payload.",
        "- `160` and `1F1` remain the compact power/body and ignition/environment",
        "  candidates to prioritize in low-rate bench context profiles.",
    ])

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote native body state deltas to {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
