#!/usr/bin/env python3
"""Summarize native Corsa E body/IPC candidate payloads from saved captures."""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
LOG_DIR = REPO_ROOT / "data" / "can_logs"
OUT_MD = REPO_ROOT / "analysis" / "generated" / "native_body_seed_summary.md"
FOCUS_IDS = ["0F1", "12A", "135", "137", "139", "160", "1F1", "451", "4E1", "514"]
LINE_RE = re.compile(r"^\((?P<ts>[0-9.]+)\)\s+\S+\s+(?P<id>[0-9A-Fa-f]+)#(?P<data>[0-9A-Fa-f]*)")


def iter_static_logs() -> list[Path]:
    return sorted(
        path
        for path in LOG_DIR.glob("*")
        if path.is_file()
        and path.suffix.lower() in {".candump", ".txt"}
        and "live" not in path.parts
    )


def parse_log(path: Path) -> dict[str, list[tuple[float, str]]]:
    rows: dict[str, list[tuple[float, str]]] = defaultdict(list)
    with path.open("r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            match = LINE_RE.match(line.strip())
            if not match:
                continue
            can_id = match.group("id").upper()
            if can_id not in FOCUS_IDS:
                continue
            rows[can_id].append((float(match.group("ts")), match.group("data").upper()))
    return rows


def median_period_ms(samples: list[tuple[float, str]]) -> str:
    if len(samples) < 2:
        return ""
    times = sorted(ts for ts, _ in samples)
    diffs = [(b - a) * 1000 for a, b in zip(times, times[1:]) if b > a]
    if not diffs:
        return ""
    diffs.sort()
    return f"{diffs[len(diffs) // 2]:.3f}"


def main() -> int:
    per_id_payloads: dict[str, Counter[str]] = {can_id: Counter() for can_id in FOCUS_IDS}
    per_file_counts: dict[str, Counter[str]] = defaultdict(Counter)
    per_id_files: dict[str, set[str]] = defaultdict(set)
    per_id_periods: dict[str, list[str]] = defaultdict(list)

    for path in iter_static_logs():
        parsed = parse_log(path)
        for can_id, samples in parsed.items():
            if not samples:
                continue
            per_id_files[can_id].add(path.name)
            per_file_counts[path.name][can_id] += len(samples)
            per_id_periods[can_id].append(median_period_ms(samples))
            per_id_payloads[can_id].update(data for _, data in samples)

    lines = [
        "# Native Body Seed Summary",
        "",
        "Generated by `tools/can_native_body_seed_miner.py` from saved non-live",
        "Corsa E captures under `data/can_logs`.",
        "",
        "These are real observed standard-ID body/IPC candidate payloads. They are",
        "better replay seeds than generic guesses, but still require the IPC to be",
        "electrically awake on the low-speed bus before bench testing.",
        "",
        "## Payloads By ID",
        "",
        "| ID | Files | Count | Median period examples ms | Top payloads |",
        "|---:|---:|---:|---|---|",
    ]

    for can_id in FOCUS_IDS:
        payloads = per_id_payloads[can_id]
        top_payloads = ", ".join(f"`{payload}` x{count}" for payload, count in payloads.most_common(8))
        period_examples = ", ".join(period for period in per_id_periods[can_id][:5] if period)
        lines.append(
            f"| `{can_id}` | {len(per_id_files[can_id])} | {sum(payloads.values())} | {period_examples} | {top_payloads} |"
        )

    lines.extend(["", "## Counts By Source File", "", "| File | " + " | ".join(f"`{can_id}`" for can_id in FOCUS_IDS) + " |", "|---|" + "---:|" * len(FOCUS_IDS)])
    for file_name, counts in sorted(per_file_counts.items()):
        if not any(counts[can_id] for can_id in FOCUS_IDS):
            continue
        lines.append("| " + file_name + " | " + " | ".join(str(counts[can_id]) for can_id in FOCUS_IDS) + " |")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote native body seed summary to {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
